sudo: required
services:
  - docker

before_install:
  - docker build -t iboretska/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true  iboretska/react-test npm test

after_success:
  - docker build -t iboretska/multi-client ./client
  - docker build -t iboretska/multi-nginx ./nginx
  - docker build -t iboretska/multi-server ./server
  - docker build -t iboretska/multi-worker ./worker
